GRNegative = ["I wish you jumped into the oven, it would make my life a lot easier", 
"I've never ever, ever, ever met someone I believe in as little as you",
"My gran could do better! And she’s dead!", 
"For what we are about to eat, may the Lord make us truly not vomit.", "You’re getting your knickers in a twist! Calm down!",
"This lamb is so undercooked, it’s following Mary to school!",
"This pizza is so disgusting, if you take it to Italy you’ll get arrested.",
"There’s enough garlic in here to kill every vampire in Europe",
"This is a really tough decision…’cause you’re both crap.",
"After trying Hawaiian pizza: “This isn’t a pizza, this is a mistake. This is an Italian tragedy.",
"Why did the chicken cross the road? Because you didn’t freaking cook it!",
"You put so much ginger in this, it’s a Weasley.",
"Stop taking things personally.",
"Swearing is industry language. For as long as we’re alive it’s not going to change. You’ve got to be boisterous to get results.", 
"Don't just stand there like a big freaking muffin!",
"That's common sense Joe! And your tiny mind is not common!",
"'What are you?', 'An idiot sandwich'",
"This crab is so undercooked I can still hear it singing ‘Under the Sea.’",
"I wouldn’t trust you running a bath",
"You surprise me as to how awful you are",
"You added so much salt and pepper I can hear the dish singing ‘Push It.’",
"Congratulations...on the worst dish in this competition so far.",
"There’s enough garlic in here to kill every vampire in Europe.",
"Hey, panini head, are you listening to me?",
"This fish is so raw it’s still finding Nemo.",
"Forecast for tomorrow? 100 percent chance of tears.",
"Honestly chimichanga… chimi chuck it in the bin.",
"You suprise me with all you ambitions...You suprise me by how awful you are",
"You freaking donut",
"I thinkn you're a plank",
"Are you stupid?",
"You're so in denial, you need therapy!",
"This is a really tough decision… ’cause you’re both crap.",
"Piss off."
      ]

GRPositive = ["I don’t like looking back. I’m always constantly looking forward. I’m not the one to sort of sit and cry over spilt milk. I’m too busy looking for the next cow", 
"I’ve had a lot of success, I’ve had failures, so I learn from the failure.", 
"Push your limit to the absolute extreme.", 
"They say cats have nine lives. I’ve had 12 already and I don’t know how many more I’ll have.", 
"I am what I am. A fighter.", 
"Best to start at the bottom & gradually climb up. It’s much more fun, too.",
"First of all, for me, the secret is in the ingredients. You don’t need to start spending fortunes on organic foods and start becoming way over budget. The better the ingredient, the littler that needs doing to it.",
"Put your head down and work hard. Never wait for things to happen, make them happen for yourself through hard graft and not giving up.",
]